# Generated by Django 2.2.17 on 2021-04-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='title',
            field=models.CharField(default='meme', max_length=128),
        ),
    ]
