# Generated by Django 2.2.17 on 2021-04-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_meme_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
