# Generated by Django 2.2.17 on 2021-04-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_auto_20210404_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meme',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
