# Generated by Django 2.2.17 on 2021-04-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0005_auto_20210404_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
